### ISSUE TITLE
Usage with React Native

### ISSUE THREAD

**Issue by areebvohra** [martyan/react-customizable-progressbar#1]
hello sir,
amazing work you have done here.
i wanted to ask can this be done on react-native?
i tried to use it in react-native but hit a road block.
 could you help me with this.

thank you

**Comment by martyan** [comment]
Hi Areeb, thank you for using RCP! 

Unfortunately this component can't be used in React Native as it would need a code rewrite.

Feel free if you're willing to rewrite it. Otherwise I would recommend using some of the already working & tested solutions for React Native such as:

https://github.com/bartgryszko/react-native-circular-progress
https://github.com/MrToph/react-native-progress-circle

Cheers!
Martin

**Comment by areebvohra** [comment]
i tried those packages
but they don't have the pointer like in your package.

![capture](https://user-images.githubusercontent.com/34376767/63578034-12f98c80-c5a9-11e9-8c18-c2de3482e357.PNG)

**Comment by martyan** [comment]
Sorry Areeb, can't help :/ 
Closing as out of scope
